[package]
name = "sci-lisp"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = ""
repository = "https://github.com/chaploud/sci-lisp"
documentation = ""
description = "A Lisp for Scientific Computation written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
linefeed = {version = "0.6.0"}
pest = "2.1"
pest_derive = "2.1"

[[bin]]
name = "scilisp"
path = "src/main.rs"
