// lexer.pest
WHITESPACE = _{ " " | "\t" | "\r" | "\n" | "," }
COMMENT = _{ ";" ~ (!"\n" ~ ANY)* ~ "\n" }

string = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
regex = @{ "#" ~ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
bool = @{ "true" | "false" }
nil = @{ "nil" }
integer = @{ ('-' | '+')? ~ ASCII_DIGIT+ }
float = @{ ('-' | '+')? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? ~ ("e" ~ ('-' | '+')? ~ ASCII_DIGIT+)? | "nan" | "inf" | "-inf" | "+inf" | "-0." ~ ("0")* }
keyword = @{ ":" ~ symbol }
symbol = @{ "'" ~ (ASCII_ALPHABETIC | "_") ~ (ASCII_ALPHANUMERIC | "_" | "-" | "*")* }
list = @{ "(" ~ expr* ~ ")" }
vector = @{ "[" ~ expr* ~ "]" }
hashmap = @{ "{" ~ (expr ~ expr)* ~ "}" }
hashset = @{ "#{" ~ expr* ~ "}" }
quote = @{ "'" ~ expr }
backquote = @{ "`" ~ expr }
unquote = @{ "~" ~ expr }
unquote_splicing = @{ "~@" ~ expr }
expr = _{ COMMENT | string | regex | bool | nil | integer | float | keyword | symbol | list | vector | hashmap | hashset | quote | backquote | unquote | unquote_splicing }
program = { SOI ~ expr* ~ EOI }

